### ISSUE TITLE
header is filled with data from the content when no meta description given

### ISSUE THREAD

**Issue by hezide** [Yoast/Yoast-SEO-for-Magento2#38] opened 2017-07-03 17:44 UTC
Hi,
I know I can just solve this by adding meta description and I will, but just reporting so you will know about it.

If the meta description is empty:
![default](https://user-images.githubusercontent.com/22726977/27803048-3035ffa8-6030-11e7-9790-13193de543fe.PNG)

in product page I see the data from the content in the header : 
![2](https://user-images.githubusercontent.com/22726977/27803074-52b42122-6030-11e7-91eb-f91830b76291.PNG)

**Comment by vincenthornikx** [comment] 2017-09-20 11:45
Hi @hezide,
I can't reproduce this issue. Could you send (a snippet from) your output HTML where this occurs?
I'm mostly interested in the head section.

**Comment by royvanos** [comment] 2017-10-10 12:42
We seem to have this issue in all shops that use this module, it only seems to happen when a category has a meta, but hasn't been edited with the snippet editor.

If you still need some HTML output, just ask!

**Comment by royvanos** [comment] 2017-12-15 10:10
@vincenthornikx I think I've found the issue! 

This only seems to happen when there's HTML elements with attributes in the category description, so for example putting `<p>test</p>` in the category description works fine, but adding an attribute like `<p class="this-breaks-stuff">test</p>` breaks stuff.

Replacing the double quotes with single quotes doesn't work either because Magento 2 seems to santize the input and converts single quotes to double quotes.

This issue happens because adding a double quote to an attribute tag "closes" the attribute value.

**Comment by vincenthornikx** [comment] 2018-01-12 06:39
@royvanos thanks for your feedback. this will be included in the 1.1.2 release

**Closed** 2018-01-12 06:39 UTC
Labels: bug, question
